// Copyright (c) 2017 Patrik Bachan
//
// GNU GENERAL PUBLIC LICENSE
//    Version 3, 29 June 2007
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.



#include "gpio.h"

const gpio_port_bit_t *LED1 = GPIO_PORT_BIT(GPIOG,9);
const gpio_port_bit_t *LED2 = GPIO_PORT_BIT(GPIOD,7);
const gpio_port_bit_t *LED3 = GPIO_PORT_BIT(GPIOD,5);
const gpio_port_bit_t *LED4 = GPIO_PORT_BIT(GPIOD,4);
const gpio_port_bit_t *LCD_nRST = GPIO_PORT_BIT(GPIOE,3);


//---------------- SWD ---------------
// SWDIO
#define PA_13_MODE		GPIO_MODE_ALTERNATE
#define PA_13_AF		GPIO_AF0
// SWCLK
#define PA_14_MODE		GPIO_MODE_ALTERNATE
#define PA_14_AF		GPIO_AF0
// SWO
#define PB_3_MODE		GPIO_MODE_ALTERNATE
#define PB_3_AF			GPIO_AF0

//---------------- LEDs ---------------
// LED1 (BLUE)
#define PG_9_MODE	GPIO_MODE_OUTPUT
#define PG_9_DEFAULT_STATE 0

// LED2 (GREEN)
#define PD_7_MODE	GPIO_MODE_OUTPUT
#define PD_7_DEFAULT_STATE 0

// LED3 (ORANGE)
#define PD_5_MODE	GPIO_MODE_OUTPUT
#define PD_5_DEFAULT_STATE 0

// LED4 (RED)
#define PD_4_MODE	GPIO_MODE_OUTPUT
#define PD_4_DEFAULT_STATE 0

//---------------- BUTTONS ---------------

//BUTTON A1
#define PH_6_MODE	GPIO_MODE_INPUT

//BUTTON A2
#define PH_7_MODE	GPIO_MODE_INPUT

//BUTTON A3
#define PB_14_MODE	GPIO_MODE_INPUT

//BUTTON B1
#define PB_15_MODE	GPIO_MODE_INPUT

//BUTTON B2
#define PD_11_MODE	GPIO_MODE_INPUT

//BUTTON B3
#define PA_8_MODE	GPIO_MODE_INPUT


//---------------- QEI1 ---------------
// A (lvl)
#define PA_0_MODE		GPIO_MODE_INPUT

// B (edge)
#define PA_2_MODE		GPIO_MODE_INPUT

// button
#define PH_2_MODE		GPIO_MODE_INPUT

//---------------- QEI1 ---------------
// A (lvl)
#define PH_3_MODE		GPIO_MODE_INPUT

// B (edge)
#define PH_4_MODE		GPIO_MODE_INPUT

// button
#define PH_5_MODE		GPIO_MODE_INPUT

//---------------- AIN1 ---------------
#define PC_4_MODE		GPIO_MODE_ANALOG

//---------------- AIN2 ---------------
#define PC_5_MODE		GPIO_MODE_ANALOG

//---------------- CAN1 ---------------
//RX
#define PA_11_MODE		GPIO_MODE_ALTERNATE
#define PA_11_AF		GPIO_AF9
#define PA_11_OSPEED	GPIO_OSPEED_HIGH
//TX
#define PA_12_MODE		GPIO_MODE_ALTERNATE
#define PA_12_AF		GPIO_AF9
#define PA_12_OSPEED	GPIO_OSPEED_HIGH

//---------------- CAN2 ---------------
//RX
#define PB_12_MODE		GPIO_MODE_ALTERNATE
#define PB_12_AF		GPIO_AF9
#define PB_12_OSPEED	GPIO_OSPEED_HIGH
//TX
#define PB_13_MODE		GPIO_MODE_ALTERNATE
#define PB_13_AF		GPIO_AF9
#define PB_13_OSPEED	GPIO_OSPEED_HIGH

//----------------- TC ----------------

// TC int
#define PA_9_MODE		GPIO_MODE_INPUT
#define PA_9_PUPD		GPIO_PUPD_PD //to ensure INT low during reset and select correct address

// TC nRST
#define PA_10_MODE		GPIO_MODE_OUTPUT
#define PA_10_DEFAULT_STATE	0

// I2C4 SDA
#define PD_13_MODE		GPIO_MODE_ALTERNATE
#define PD_13_AF		GPIO_AF4
#define PD_13_OTYPE		GPIO_OTYPE_OD
#define PD_13_DEFAULT_STATE	1

// I2C4 SCL
#define PD_12_MODE		GPIO_MODE_ALTERNATE
#define PD_12_AF		GPIO_AF4
#define PD_12_OTYPE		GPIO_OTYPE_OD
#define PD_12_DEFAULT_STATE	1

//----------------- LCD ---------------

// SPI4_MISO
#define PE_5_MODE		GPIO_MODE_ALTERNATE
#define PE_5_AF			GPIO_AF5
// SPI4_MOSI
#define PE_6_MODE		GPIO_MODE_ALTERNATE
#define PE_6_AF			GPIO_AF5
// SPI4_SCK
#define PE_2_MODE		GPIO_MODE_ALTERNATE
#define PE_2_AF			GPIO_AF5
// LCD nCS
#define PE_4_MODE		GPIO_MODE_OUTPUT
#define PE_4_DEFAULT_STATE 1

// BACKLIGHT
#define PA_15_MODE		GPIO_MODE_OUTPUT
#define PA_15_DEFAULT_STATE 0

// LCD_nRST
#define PE_3_MODE		GPIO_MODE_OUTPUT
#define PE_3_DEFAULT_STATE 0

//LTDC
// LTDC_B2
#define PD_6_MODE		GPIO_MODE_ALTERNATE
#define PD_6_AF			GPIO_AF14
#define PD_6_OSPEED		GPIO_OSPEED_HIGH
// LTDC_B3
#define PG_11_MODE		GPIO_MODE_ALTERNATE
#define PG_11_AF		GPIO_AF14
#define PG_11_OSPEED	GPIO_OSPEED_HIGH
// LTDC_B4
#define PG_12_MODE		GPIO_MODE_ALTERNATE
#define PG_12_AF		GPIO_AF9
#define PG_12_OSPEED	GPIO_OSPEED_HIGH
// LTDC_B5
#define PA_3_MODE		GPIO_MODE_ALTERNATE
#define PA_3_AF			GPIO_AF14
#define PA_3_OSPEED		GPIO_OSPEED_HIGH
// LTDC_B6
#define PB_8_MODE		GPIO_MODE_ALTERNATE
#define PB_8_AF			GPIO_AF14
#define PB_8_OSPEED		GPIO_OSPEED_HIGH
// LTDC_B7
#define PB_9_MODE		GPIO_MODE_ALTERNATE
#define PB_9_AF			GPIO_AF14
#define PB_9_OSPEED		GPIO_OSPEED_HIGH
// LTDC_CLK
#define PG_7_MODE		GPIO_MODE_ALTERNATE
#define PG_7_AF			GPIO_AF14
#define PG_7_OSPEED		GPIO_OSPEED_HIGH
// LTDC_DE
#define PF_10_MODE		GPIO_MODE_ALTERNATE
#define PF_10_AF		GPIO_AF14
#define PF_10_OSPEED	GPIO_OSPEED_HIGH
// LTDC_G2
#define PA_6_MODE		GPIO_MODE_ALTERNATE
#define PA_6_AF			GPIO_AF14
#define PA_6_OSPEED		GPIO_OSPEED_HIGH
// LTDC_G3
#define PG_10_MODE		GPIO_MODE_ALTERNATE
#define PG_10_AF		GPIO_AF9
#define PG_10_OSPEED	GPIO_OSPEED_HIGH
// LTDC_G4
#define PB_10_MODE		GPIO_MODE_ALTERNATE
#define PB_10_AF		GPIO_AF14
#define PB_10_OSPEED	GPIO_OSPEED_HIGH
// LTDC_G5
#define PB_11_MODE		GPIO_MODE_ALTERNATE
#define PB_11_AF		GPIO_AF14
#define PB_11_OSPEED	GPIO_OSPEED_HIGH
// LTDC_G6
#define PC_7_MODE		GPIO_MODE_ALTERNATE
#define PC_7_AF			GPIO_AF14
#define PC_7_OSPEED		GPIO_OSPEED_HIGH
// LTDC_G7
#define PD_3_MODE		GPIO_MODE_ALTERNATE
#define PD_3_AF			GPIO_AF14
#define PD_3_OSPEED		GPIO_OSPEED_HIGH
// LTDC_HSYNC
#define PC_6_MODE		GPIO_MODE_ALTERNATE
#define PC_6_AF			GPIO_AF14
#define PC_6_OSPEED		GPIO_OSPEED_HIGH
// LTDC_R2
#define PA_1_MODE		GPIO_MODE_ALTERNATE
#define PA_1_AF			GPIO_AF14
#define PA_1_OSPEED		GPIO_OSPEED_HIGH
// LTDC_R3
#define PB_0_MODE		GPIO_MODE_ALTERNATE
#define PB_0_AF			GPIO_AF9
#define PB_0_OSPEED		GPIO_OSPEED_HIGH
// LTDC_R4
#define PA_5_MODE		GPIO_MODE_ALTERNATE
#define PA_5_AF			GPIO_AF14
#define PA_5_OSPEED		GPIO_OSPEED_HIGH
// LTDC_R5
#define PC_0_MODE		GPIO_MODE_ALTERNATE
#define PC_0_AF			GPIO_AF14
#define PC_0_OSPEED		GPIO_OSPEED_HIGH
// LTDC_R6
#define PB_1_MODE		GPIO_MODE_ALTERNATE
#define PB_1_AF			GPIO_AF9
#define PB_1_OSPEED		GPIO_OSPEED_HIGH
// LTDC_R7
#define PG_6_MODE		GPIO_MODE_ALTERNATE
#define PG_6_AF			GPIO_AF14
#define PG_6_OSPEED		GPIO_OSPEED_HIGH
// LTDC_VSYNC
#define PA_4_MODE		GPIO_MODE_ALTERNATE
#define PA_4_AF			GPIO_AF14
#define PA_4_OSPEED		GPIO_OSPEED_HIGH

//SDRAM
//FMC_A0
#define PF_0_MODE	GPIO_MODE_ALTERNATE
#define PF_0_AF		GPIO_AF12
#define PF_0_OSPEED	GPIO_OSPEED_HIGH
//FMC_A1
#define PF_1_MODE	GPIO_MODE_ALTERNATE
#define PF_1_AF		GPIO_AF12
#define PF_1_OSPEED	GPIO_OSPEED_HIGH
//FMC_A2
#define PF_2_MODE	GPIO_MODE_ALTERNATE
#define PF_2_AF		GPIO_AF12
#define PF_2_OSPEED	GPIO_OSPEED_HIGH
//FMC_A3
#define PF_3_MODE	GPIO_MODE_ALTERNATE
#define PF_3_AF		GPIO_AF12
#define PF_3_OSPEED	GPIO_OSPEED_HIGH
//FMC_A4
#define PF_4_MODE	GPIO_MODE_ALTERNATE
#define PF_4_AF		GPIO_AF12
#define PF_4_OSPEED	GPIO_OSPEED_HIGH
//FMC_A5
#define PF_5_MODE	GPIO_MODE_ALTERNATE
#define PF_5_AF		GPIO_AF12
#define PF_5_OSPEED	GPIO_OSPEED_HIGH
//FMC_A6
#define PF_12_MODE	GPIO_MODE_ALTERNATE
#define PF_12_AF	GPIO_AF12
#define PF_12_OSPEED	GPIO_OSPEED_HIGH
//FMC_A7
#define PF_13_MODE	GPIO_MODE_ALTERNATE
#define PF_13_AF	GPIO_AF12
#define PF_13_OSPEED	GPIO_OSPEED_HIGH
//FMC_A8
#define PF_14_MODE	GPIO_MODE_ALTERNATE
#define PF_14_AF	GPIO_AF12
#define PF_14_OSPEED	GPIO_OSPEED_HIGH
//FMC_A9
#define PF_15_MODE	GPIO_MODE_ALTERNATE
#define PF_15_AF	GPIO_AF12
#define PF_15_OSPEED	GPIO_OSPEED_HIGH
//FMC_A10
#define PG_0_MODE	GPIO_MODE_ALTERNATE
#define PG_0_AF		GPIO_AF12
#define PG_0_OSPEED	GPIO_OSPEED_HIGH
//FMC_A11
#define PG_1_MODE	GPIO_MODE_ALTERNATE
#define PG_1_AF		GPIO_AF12
#define PG_1_OSPEED	GPIO_OSPEED_HIGH
//FMC_A12
#define PG_2_MODE	GPIO_MODE_ALTERNATE
#define PG_2_AF		GPIO_AF12
#define PG_2_OSPEED	GPIO_OSPEED_HIGH
//FMC_A13
#define PG_3_MODE	GPIO_MODE_ALTERNATE
#define PG_3_AF		GPIO_AF12
#define PG_3_OSPEED	GPIO_OSPEED_HIGH
//FMC_BA0
#define PG_4_MODE	GPIO_MODE_ALTERNATE
#define PG_4_AF		GPIO_AF12
#define PG_4_OSPEED	GPIO_OSPEED_HIGH
//FMC_BA1
#define PG_5_MODE	GPIO_MODE_ALTERNATE
#define PG_5_AF		GPIO_AF12
#define PG_5_OSPEED	GPIO_OSPEED_HIGH
//FMC_D0
#define PD_14_MODE	GPIO_MODE_ALTERNATE
#define PD_14_AF	GPIO_AF12
#define PD_14_OSPEED	GPIO_OSPEED_HIGH
//FMC_D1
#define PD_15_MODE	GPIO_MODE_ALTERNATE
#define PD_15_AF	GPIO_AF12
#define PD_15_OSPEED	GPIO_OSPEED_HIGH
//FMC_D2
#define PD_0_MODE	GPIO_MODE_ALTERNATE
#define PD_0_AF		GPIO_AF12
#define PD_0_OSPEED	GPIO_OSPEED_HIGH
//FMC_D3
#define PD_1_MODE	GPIO_MODE_ALTERNATE
#define PD_1_AF		GPIO_AF12
#define PD_1_OSPEED	GPIO_OSPEED_HIGH
//FMC_D4
#define PE_7_MODE	GPIO_MODE_ALTERNATE
#define PE_7_AF		GPIO_AF12
#define PE_7_OSPEED	GPIO_OSPEED_HIGH
//FMC_D5
#define PE_8_MODE	GPIO_MODE_ALTERNATE
#define PE_8_AF		GPIO_AF12
#define PE_8_OSPEED	GPIO_OSPEED_HIGH
//FMC_D6
#define PE_9_MODE	GPIO_MODE_ALTERNATE
#define PE_9_AF		GPIO_AF12
#define PE_9_OSPEED	GPIO_OSPEED_HIGH
//FMC_D7
#define PE_10_MODE	GPIO_MODE_ALTERNATE
#define PE_10_AF	GPIO_AF12
#define PE_10_OSPEED	GPIO_OSPEED_HIGH
//FMC_D8
#define PE_11_MODE	GPIO_MODE_ALTERNATE
#define PE_11_AF	GPIO_AF12
#define PE_11_OSPEED	GPIO_OSPEED_HIGH
//FMC_D9
#define PE_12_MODE	GPIO_MODE_ALTERNATE
#define PE_12_AF	GPIO_AF12
#define PE_12_OSPEED	GPIO_OSPEED_HIGH
//FMC_D10
#define PE_13_MODE	GPIO_MODE_ALTERNATE
#define PE_13_AF	GPIO_AF12
#define PE_13_OSPEED	GPIO_OSPEED_HIGH
//FMC_D11
#define PE_14_MODE	GPIO_MODE_ALTERNATE
#define PE_14_AF	GPIO_AF12
#define PE_14_OSPEED	GPIO_OSPEED_HIGH
//FMC_D12
#define PE_15_MODE	GPIO_MODE_ALTERNATE
#define PE_15_AF	GPIO_AF12
#define PE_15_OSPEED	GPIO_OSPEED_HIGH
//FMC_D13
#define PD_8_MODE	GPIO_MODE_ALTERNATE
#define PD_8_AF		GPIO_AF12
#define PD_8_OSPEED	GPIO_OSPEED_HIGH
//FMC_D14
#define PD_9_MODE	GPIO_MODE_ALTERNATE
#define PD_9_AF		GPIO_AF12
#define PD_9_OSPEED	GPIO_OSPEED_HIGH
//FMC_D15
#define PD_10_MODE	GPIO_MODE_ALTERNATE
#define PD_10_AF	GPIO_AF12
#define PD_10_OSPEED	GPIO_OSPEED_HIGH
//FMC_D16
#define PH_8_MODE	GPIO_MODE_ALTERNATE
#define PH_8_AF		GPIO_AF12
#define PH_8_OSPEED	GPIO_OSPEED_HIGH
//FMC_D17
#define PH_9_MODE	GPIO_MODE_ALTERNATE
#define PH_9_AF		GPIO_AF12
#define PH_9_OSPEED	GPIO_OSPEED_HIGH
//FMC_D18
#define PH_10_MODE	GPIO_MODE_ALTERNATE
#define PH_10_AF	GPIO_AF12
#define PH_10_OSPEED	GPIO_OSPEED_HIGH
//FMC_D19
#define PH_11_MODE	GPIO_MODE_ALTERNATE
#define PH_11_AF	GPIO_AF12
#define PH_11_OSPEED	GPIO_OSPEED_HIGH
//FMC_D20
#define PH_12_MODE	GPIO_MODE_ALTERNATE
#define PH_12_AF	GPIO_AF12
#define PH_12_OSPEED	GPIO_OSPEED_HIGH
//FMC_D21
#define PH_13_MODE	GPIO_MODE_ALTERNATE
#define PH_13_AF	GPIO_AF12
#define PH_13_OSPEED	GPIO_OSPEED_HIGH
//FMC_D22
#define PH_14_MODE	GPIO_MODE_ALTERNATE
#define PH_14_AF	GPIO_AF12
#define PH_14_OSPEED	GPIO_OSPEED_HIGH
//FMC_D23
#define PH_15_MODE	GPIO_MODE_ALTERNATE
#define PH_15_AF	GPIO_AF12
#define PH_15_OSPEED	GPIO_OSPEED_HIGH
//FMC_D24
#define PI_0_MODE	GPIO_MODE_ALTERNATE
#define PI_0_AF		GPIO_AF12
#define PI_0_OSPEED	GPIO_OSPEED_HIGH
//FMC_D25
#define PI_1_MODE	GPIO_MODE_ALTERNATE
#define PI_1_AF		GPIO_AF12
#define PI_1_OSPEED	GPIO_OSPEED_HIGH
//FMC_D26
#define PI_2_MODE	GPIO_MODE_ALTERNATE
#define PI_2_AF		GPIO_AF12
#define PI_2_OSPEED	GPIO_OSPEED_HIGH
//FMC_D27
#define PI_3_MODE	GPIO_MODE_ALTERNATE
#define PI_3_AF		GPIO_AF12
#define PI_3_OSPEED	GPIO_OSPEED_HIGH
//FMC_D28
#define PI_6_MODE	GPIO_MODE_ALTERNATE
#define PI_6_AF		GPIO_AF12
#define PI_6_OSPEED	GPIO_OSPEED_HIGH
//FMC_D29
#define PI_7_MODE	GPIO_MODE_ALTERNATE
#define PI_7_AF		GPIO_AF12
#define PI_7_OSPEED	GPIO_OSPEED_HIGH
//FMC_D30
#define PI_9_MODE	GPIO_MODE_ALTERNATE
#define PI_9_AF		GPIO_AF12
#define PI_9_OSPEED	GPIO_OSPEED_HIGH
//FMC_D31
#define PI_10_MODE	GPIO_MODE_ALTERNATE
#define PI_10_AF	GPIO_AF12
#define PI_10_OSPEED	GPIO_OSPEED_HIGH
//FMC_NBL0
#define PE_0_MODE	GPIO_MODE_ALTERNATE
#define PE_0_AF		GPIO_AF12
#define PE_0_OSPEED	GPIO_OSPEED_HIGH
//FMC_NBL1
#define PE_1_MODE	GPIO_MODE_ALTERNATE
#define PE_1_AF		GPIO_AF12
#define PE_1_OSPEED	GPIO_OSPEED_HIGH
//FMC_NBL2
#define PI_4_MODE	GPIO_MODE_ALTERNATE
#define PI_4_AF		GPIO_AF12
#define PI_4_OSPEED	GPIO_OSPEED_HIGH
//FMC_NBL3
#define PI_5_MODE	GPIO_MODE_ALTERNATE
#define PI_5_AF		GPIO_AF12
#define PI_5_OSPEED	GPIO_OSPEED_HIGH
//FMC_SDCKE0
#define PC_3_MODE	GPIO_MODE_ALTERNATE
#define PC_3_AF		GPIO_AF12
#define PC_3_OSPEED	GPIO_OSPEED_HIGH
//FMC_SDCLK
#define PG_8_MODE	GPIO_MODE_ALTERNATE
#define PG_8_AF		GPIO_AF12
#define PG_8_OSPEED	GPIO_OSPEED_HIGH
//FMC_SDNCAS
#define PG_15_MODE	GPIO_MODE_ALTERNATE
#define PG_15_AF	GPIO_AF12
#define PG_15_OSPEED	GPIO_OSPEED_HIGH
//FMC_SDNE0
#define PC_2_MODE	GPIO_MODE_ALTERNATE
#define PC_2_AF		GPIO_AF12
#define PC_2_OSPEED	GPIO_OSPEED_HIGH
//FMC_SDNRAS
#define PF_11_MODE	GPIO_MODE_ALTERNATE
#define PF_11_AF	GPIO_AF12
#define PF_11_OSPEED	GPIO_OSPEED_HIGH
//FMC_SDNWE
#define PA_7_MODE	GPIO_MODE_ALTERNATE
#define PA_7_AF		GPIO_AF12
#define PA_7_OSPEED	GPIO_OSPEED_HIGH

#include "gpio_gen.h"






















































































































